import Head from "next/head";
import Header from "@/components/header";
import TextArea from "@/components/text-area";
import PrewiewArea from "@/components/prewiew-area";
import styles from "../styles/index.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Markdown Prewiew</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <TextArea />
        <PrewiewArea />
      </main>
    </>
  );
}
